version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: usonly
      MYSQL_ROOT_PASSWORD: your_password  # 본인 비번으로 수정
    ports:
      - "3306:3306"

  app:
    build: .  # 현재 폴더의 Dockerfile을 읽어서 빌드
    container_name: spring-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/usonly?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: your_password # 위와 동일하게